---
title: "Super Awesome Project Template"
output: word_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section One

```{r student1}

```


## Section Two

```{r student2}

```

## Section Three

```{r student3}


```



## Section Four

```{r student4}
library(rvest)
library(stringr)
library(tidyr)
library(sf)
library(tidyverse)
library(dplyr)

url="https://www2.census.gov/geo/tiger/TIGER2023/ROADS/"
x=readLines(url)
GEOID_url=x %>% str_extract(pattern="tl_2023_\\d{5}_roads.zip")
GEOID_url=na.omit(GEOID_url)
GEOID=GEOID_url %>% str_extract(pattern="\\d{5}")

Road_suffixes=c("Rd","Co Rd","Ln","St","Dr","Ct","Ave","Cir","82","Way","Loop","Pl","Blvd")

#gets all the GEOID's
my_sf2 = list()
for(i in 1:3){
  curGEOID = GEOID[i]
  GEOID_file = GEOID_url[i]
 url11=str_c("https://www2.census.gov/geo/tiger/TIGER2023/ROADS/", GEOID_file)
  d=download.file(url11, dest= curGEOID, method="auto", timeout = 120)
  unzip(curGEOID, exdir = "RoadData")
  my_sf = read_sf(dsn = "RoadData")
  
  roads=function(x) {
  my_sf$FULLNAME %>% str_which(.,x)
}
g=sapply(Road_suffixes,roads)

most=max(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir),length(g$`82`),length(g$Way),length(g$Loop),length(g$Pl),length(g$Blvd))

most_common=Road_suffixes[which(max(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir),length(g$`82`),length(g$Way),length(g$Loop),length(g$Pl),length(g$Blvd))==most)]

split=my_sf$FULLNAME %>% str_split(.,"\\s") %>% lapply(.,tail,n=1) %>% unlist()
table(split) %>% as.data.frame() %>% arrange(desc(Freq))
head(split)

d=c(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir),length(g$`82`),length(g$Way),length(g$Loop),length(g$Pl),length(g$Blvd))

names(d)=Road_suffixes
slice_max(as.data.frame(d),d,n=2) %>% rownames
temp=slice_max(as.data.frame(d),d,n=2) %>% rownames()
temp[2]


  my_sf2[[i]] = my_sf %>% mutate(GEOID = curGEOID) %>% mutate(MostCommon=most_common) %>% mutate(SecondMost=temp[2])
  file.remove(curGEOID)
  unlink("RoadData", recursive = TRUE, force = TRUE)
}
# map_df
```

```{r}
h=read_sf("tl_2023_01001_roads.shp")
h
h1=h$FULLNAME
h1=na.omit(h1)
head(h1)

Road_suffixes=c("Rd","Co Rd","Ln","St","Dr","Ct","Ave","Cir","82","way","Loop","Pl","Blvd")
roads=function(x) {
  h1 %>% str_which(.,x)
}

g=sapply(Road_suffixes,roads)

most=max(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir))

most_common=Road_suffixes[which(max(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir))==most)]


split=my_sf$FULLNAME %>% str_split(.,"\\s") %>% lapply(.,tail,n=1) %>% unlist()
table(split) %>% as.data.frame() %>% arrange(desc(Freq))
head(split)

d=c(length(g$Rd),
    length(g$`Co Rd`),length(g$Ln),length(g$St),length(g$Dr),length(g$Ct),length(g$Ave),length(g$Cir))

slice_max(d)
as.data.frame(d)
names(d)=Road_suffixes
slice_max(as.data.frame(d),d,n=2) %>% rownames
temp=slice_max(as.data.frame(d),d,n=2) %>% rownames()
temp[2]


```